### ISSUE TITLE
Export fails

### ISSUE THREAD

**Issue by arthurlutz** [cozy/cozy-calendar#245]
Trying to export a calendar I get a "It seems that something went wrong." No additional information (I can debug if needed) but the URL contains a NaN which maybe indicates a javascript problem : 

https://host:9443/#apps/calendar/week/2015/NaN/4

**Comment by clochix** [comment]
I can confirm that trying to export a calendar crashes the application, here are the logs;

```
/usr/local/cozy/apps/calendar/build/server/controllers/ical.js:29
    return res.send(calendar.toString());
                             ^
TypeError: Cannot call method 'toString' of null
    at /usr/local/cozy/apps/calendar/build/server/controllers/ical.js:29:30
    at /usr/local/cozy/apps/calendar/build/server/controllers/ical.js:50:14
    at /usr/local/cozy/apps/calendar/node_modules/cozydb/lib/model.js:200:18
    at /usr/local/cozy/apps/calendar/node_modules/cozydb/lib/cozymodel.js:254:18
    at parseBody (/usr/local/cozy/apps/calendar/node_modules/cozydb/node_modules/request-json-light/main.js:74:10)
    at IncomingMessage.<anonymous> (/usr/local/cozy/apps/calendar/node_modules/cozydb/node_modules/request-json-light/main.js:99:14)
    at IncomingMessage.emit (events.js:117:20)
    at _stream_readable.js:944:16
    at process._tickCallback (node.js:442:13)

```

**Comment by clochix** [comment]
Seems to work, 💋 @jsilvestre

**Comment by clochix** [comment]
@arthurlutz: thanks for reporting, it should have been fixed in latest version of the application. Can you test if it works for you ?
