### ISSUE TITLE
failed to open cozy-calendar app on cozy-light platform.

### ISSUE THREAD

**Issue by simpzan** [cozy/cozy-calendar#297]
```
Connect
500 Error: Failed to lookup view "index.jade" in views directory "./client"
at EventEmitter.app.render (/home/simpzan/.cozy-light/node_modules/cozy-calendar/node_modules/americano/node_modules/express/lib/application.js:519:17)
at ServerResponse.res.render (/home/simpzan/.cozy-light/node_modules/cozy-calendar/node_modules/americano/node_modules/express/lib/response.js:933:7)
at /home/simpzan/.cozy-light/node_modules/cozy-calendar/build/server/controllers/index.js:54:18
at /home/simpzan/.cozy-light/node_modules/cozy-calendar/node_modules/async/lib/async.js:254:17
at done (/home/simpzan/.cozy-light/node_modules/cozy-calendar/node_modules/async/lib/async.js:135:19)
at /home/simpzan/.cozy-light/node_modules/cozy-calendar/node_modules/async/lib/async.js:32:16
at /home/simpzan/.cozy-light/node_modules/cozy-calendar/node_modules/async/lib/async.js:251:21
at /home/simpzan/.cozy-light/node_modules/cozy-calendar/node_modules/async/lib/async.js:575:34
at /home/simpzan/.cozy-light/node_modules/cozy-calendar/node_modules/cozy-db-pouchdb/lib/model.js:240:16
at /home/simpzan/.cozy-light/node_modules/cozy-calendar/node_modules/cozy-db-pouchdb/lib/model.js:200:18
```

**Comment by clochix** [comment]
Hi @frankrousseau,

do you think the problem is related to Calendar or Cozy-light ?

**Comment by simpzan** [comment]
It's related to Calendar. 
the build process compile all jade files to js file, there's no jade file at all in ./client dir. but the code is rendering index.jade. that's the problem I tracked down, maybe still shallow. I am not familiar with coffeescript.

**Comment by frankrousseau** [comment]
It's the cozy-light version of Calendar which is broken. I can't figure out why it is looking for jade files. I hope @jsilvestre or @aenario could help.

**Comment by simpzan** [comment]
`index.jade` in explicitly written in code here. 
https://github.com/cozy/cozy-calendar/blob/41eca1dfc7135b480eb4529933d58eecf80abc6e/server/controllers/index.coffee#L35

**Comment by frankrousseau** [comment]
Awesome. Thank you. I was only looking at Americano config. It got me mad. I will look at it.

**Comment by frankrousseau** [comment]
Finally it's fixed. Could you try again?

**Comment by simpzan** [comment]
It's working now. Thanks!
