### ISSUE TITLE
Wrong time for events from Outlook CALDav plugin

### ISSUE THREAD

**Issue by drschwabe** [cozy/cozy-calendar#425]
Is anyone else using Cozy in combination with Outlook ?  (via https://github.com/aluxnimm/outlookcaldavsynchronizer)

We are getting incorrect times.  For example, you create an event in Outlook and when the event is synced to the server the time is off by 6 hours.   Even though in Outlook, even after closing the program and loading it back up (syncing to the server again), the time appears correct.  

Possibly has something to do with sync, in the sync logs this error is shown: 

```
Deprecation warning: moment().zone is deprecated, use moment().utcOffset instead. https://github.com/moment/moment/issues/1779
Error
    at Moment.zone (/usr/local/cozy/apps/sync/node_modules/cozy-ical/node_modules/moment-timezone/node_modules/moment/moment.js:746:36)
    at Function.moment.updateOffset (/usr/local/cozy/apps/sync/node_modules/cozy-ical/node_modules/moment-timezone/moment-timezone.js:352:8)
    at Moment.fn.tz (/usr/local/cozy/apps/sync/node_modules/cozy-ical/node_modules/moment-timezone/moment-timezone.js:360:12)
    at Function.tz (/usr/local/cozy/apps/sync/node_modules/cozy-ical/node_modules/moment-timezone/moment-timezone.js:315:7)
    at ModelConstructor.Event.toIcal (/usr/local/cozy/apps/sync/node_modules/cozy-ical/lib/event.js:35:24)
    at CozyCalDAVBackend.module.exports.CozyCalDAVBackend._toICal (/usr/local/cozy/apps/sync/build/server/backends/caldav.js:126:17)
    at /usr/local/cozy/apps/sync/build/server/backends/caldav.js:316:26
    at /usr/local/cozy/apps/sync/node_modules/async/lib/async.js:232:13
    at /usr/local/cozy/apps/sync/node_modules/async/lib/async.js:119:25
    at /usr/local/cozy/apps/sync/node_modules/async/lib/async.js:24:16

TypeError: Cannot read property '0' of undefined
    at /usr/local/cozy/apps/sync/build/server/backends/caldav.js:172:35
    at /usr/local/cozy/apps/sync/node_modules/americano-cozy/node_modules/jugglingdb-cozy-adapter/lib/cozy_data_system.js:520:20
    at parseBody (/usr/local/cozy/apps/sync/node_modules/americano-cozy/node_modules/jugglingdb-cozy-adapter/node_modules/request-json/main.js:26:12)
    at Request._callback (/usr/local/cozy/apps/sync/node_modules/americano-cozy/node_modules/jugglingdb-cozy-adapter/node_modules/request-json/main.js:81:18)
    at self.callback (/usr/local/cozy/apps/sync/node_modules/americano-cozy/node_modules/jugglingdb-cozy-adapter/node_modules/request-json/node_modules/request/index.js:148:22)
    at Request.EventEmitter.emit (events.js:95:17)
    at ClientRequest.self.clientErrorHandler (/usr/local/cozy/apps/sync/node_modules/americano-cozy/node_modules/jugglingdb-cozy-adapter/node_modules/request-json/node_modules/request/index.js:257:10)
    at ClientRequest.EventEmitter.emit (events.js:95:17)
    at Socket.socketOnEnd [as onend] (http.js:1568:9)
    at Socket.g (events.js:180:16)
[2015-09-25 12:47:11:723] error - americano-cozy | failed Error: connect ECONNREFUSED
[2015-09-25 12:47:11:724] error - americano-cozy | A request creation failed, abandon.
[2015-09-25 12:47:11:725] error - americano | americano-cozy failed to load.
```

**Comment by drschwabe** [comment]
Syncing from iPhone works fine - only seeing the odd timing with events from Outlook.

**Comment by aenario** [comment]
Hi @drschwabe, thanks for experimenting with outlook and reporting your bug.

This sounds like a timezone bug, could you tell us 
1 - the timezone your computer running outlook is in.
2 - the timezone your cozy server is configured in (visible through the settings page of your cozy home)

Also, just to be sure, are you running outlookcaldavsynchronizer > 0.99.3 ? It appears there was some TZ issues in older versions.

**Comment by drschwabe** [comment]
1) The computer running Outlook, is on (UTC-07:00) Mountain Time (US & Canada)
2) Timezone in Cozy is America/Edmonton

Using the latest release of outlookcaldavsynchronizer 1.2.2

Thanks.

**Comment by aenario** [comment]
Thanks for the details, we will take a look at this when we have some time.

**Comment by drschwabe** [comment]
I cross posted the issue to the Outlook CalDav plugin repo.  Between all of us maybe we can solve the problem: 

https://github.com/aluxnimm/outlookcaldavsynchronizer/issues/66

**Comment by Dinduks** [comment]
Hi,

I updated the issue mentioned above: https://github.com/aluxnimm/outlookcaldavsynchronizer/issues/66#issuecomment-233198276 :blush:

**Comment by terrycloth** [comment]
I think I have the same issue, but with Evolution, the standard email and calendar application for GNOME desktop. New appointments change by 7 hours on save -- which matches the time zone difference between me (Pacific Daylight Time, in the US) and the cozycloud.cc servers (which are in France, I assume).

I originally reported my problem to the Evolution developers. They said:

> The conversion of the TZID is all fine, but the server also changed the times, from 12:00 to 05:00 for the DTSTART and similarly from 13:00 to 06:00 for the DTEND.

See the GNOME Bugzilla thread for some more debugging information.

https://bugzilla.gnome.org/show_bug.cgi?id=768750#c6

**Comment by jsilvestre** [comment]
This bug is due to the fact Cozy doesn't work well with timezones. It is an issue independent of the client used.

**Comment by Dinduks** [comment]
This bug was apparently fixed in https://github.com/aluxnimm/outlookcaldavsynchronizer/issues/66#issuecomment-243001972.

Could you please update us regarding the fix in Cozy?

Thanks!

**Comment by jsilvestre** [comment]
If they changed the timezone to be in the "standard" list (like Europe/Paris) it will work as-is. If it still requires VTIMEZONE support, I am afraid you will have to wait a bit longer that we develop it (which is somewhere on the roadmap).
