### ISSUE TITLE
[client] TypeError: this.source[0] is undefined

### ISSUE THREAD

**Issue by clochix** [cozy/cozy-calendar#467]
```
TypeError: this.source[0] is undefined
    at ComboBox</ComboBox.prototype.getDefaultValue@https://xxxx.cozycloud.cc/apps/calendar/javascripts/app.js:7554:5
    at ComboBox</ComboBox.prototype.initialize@https://xxxx.cozycloud.cc/apps/calendar/javascripts/app.js:7542:32
    at Backbone.View@https://xxxx.cozycloud.cc/apps/calendar/javascripts/vendor.js:20875:5
    at BaseView@https://xxxx.cozycloud.cc/apps/calendar/javascripts/app.js:1111:12
    at ComboBox@https://xxxx.cozycloud.cc/apps/calendar/javascripts/app.js:7507:12
    at SettingsModals</SettingsModals.prototype.afterRender@https://xxxx.cozycloud.cc/apps/calendar/javascripts/app.js:6733:21
    at BaseView</BaseView.prototype.render@https://xxxx.cozycloud.cc/apps/calendar/javascripts/app.js:1128:5
    at Router</Router.prototype.settings@https://xxxx.cozycloud.cc/apps/calendar/javascripts/app.js:3953:5
    at .execute@https://xxxx.cozycloud.cc/apps/calendar/javascripts/vendor.js:21139:21
    at .route/<@https://xxxx.cozycloud.cc/apps/calendar/javascripts/vendor.js:21128:9
    at .loadUrl/<@https://xxxx.cozycloud.cc/apps/calendar/javascripts/vendor.js:21355:11
    at _.any@https://xxxx.cozycloud.cc/apps/calendar/javascripts/vendor.js:18854:1
    at .loadUrl@https://xxxx.cozycloud.cc/apps/calendar/javascripts/vendor.js:21353:1
    at .checkUrl@https://xxxx.cozycloud.cc/apps/calendar/javascripts/vendor.js:21345:7
    at jQuery.event.dispatch@https://xxxx.cozycloud.cc/apps/calendar/javascripts/vendor.js:4519:15
    at jQuery.event.add/elemData.handle@https://xxxx.cozycloud.cc/apps/calendar/javascripts/vendor.js:4206:6
```

**Comment by jsilvestre** [comment]
Do you have any information about when/how did it happen?

**Comment by clochix** [comment]
Sorry, I just saw this message in server error logs, I don't know anything about the context :-S

**Comment by clochix** [comment]
Closing, duplicate of #468
