### ISSUE TITLE
[client] TypeError: Cannot read property 'label' of undefined

### ISSUE THREAD

**Issue by clochix** [cozy/cozy-calendar#468]
```
TypeError: Cannot read property 'label' of undefined
    at ComboBox.module.exports.ComboBox.getDefaultValue (https://xxxx.cozycloud.cc/apps/calendar/javascripts/app.js:7554:26)
    at ComboBox.module.exports.ComboBox.initialize (https://xxxx.cozycloud.cc/apps/calendar/javascripts/app.js:7542:37)
    at ComboBox.Backbone.View (https://xxxx.cozycloud.cc/apps/calendar/javascripts/vendor.js:20875:21)
    at ComboBox.BaseView [as constructor] (https://xxxx.cozycloud.cc/apps/calendar/javascripts/app.js:1111:43)
    at new ComboBox (https://xxxx.cozycloud.cc/apps/calendar/javascripts/app.js:7507:43)
    at SettingsModals.module.exports.SettingsModals.afterRender (https://xxxx.cozycloud.cc/apps/calendar/javascripts/app.js:6733:21)
    at SettingsModals.module.exports.BaseView.render (https://xxxx.cozycloud.cc/apps/calendar/javascripts/app.js:1128:10)
    at Router.module.exports.Router.settings (https://xxxx.cozycloud.cc/apps/calendar/javascripts/app.js:3953:10)
    at Router._.extend.execute (https://xxxx.cozycloud.cc/apps/calendar/javascripts/vendor.js:21139:30)
    at Object.callback (https://xxxx.cozycloud.cc/apps/calendar/javascripts/vendor.js:21128:16)
```

**Comment by jsilvestre** [comment]
Do you have any information about when/how did it happen?

**Comment by clochix** [comment]
Sorry, I just saw this message in server error logs, I don't know anything about the context :-S

**Comment by clochix** [comment]
I managed to reproduce, this happens when the user delete all its calendars and try to create an event.
Not sure of what we should do in this case…

**Comment by clochix** [comment]
Just using the default calendar name if there's no calendar seems to do the job.

**Comment by poupotte** [comment]
This issue is now fixed. Thanks @clochix !
