### ISSUE TITLE
Error importing calendars from Google Takeout

### ISSUE THREAD

**Issue by mjog** [cozy/cozy-calendar#496]
I exported my Google calendars via Google Takeout because the Cozy import app only imported one calendar of the four that I have, but importing the ICS any of them from the Takeout zip caused the following error to be thrown:

```
[2016-03-13 04:47:46:756] error - calendar:ical | Error: Invalid options: bynmonthday, bynweekday
    at Object.RRule (/usr/local/cozy/apps/calendar/node_modules/cozy-ical/node_modules/rrule/lib/rrule.js:484:15)
    at Function.Event.fromIcal (/usr/local/cozy/apps/calendar/node_modules/cozy-ical/lib/event.js:111:19)
    at /usr/local/cozy/apps/calendar/node_modules/cozy-ical/lib/event.js:185:34
    at VEvent.module.exports.VComponent.VComponent.walk (/usr/local/cozy/apps/calendar/node_modules/cozy-ical/lib/index.js:149:5)
    at VCalendar.module.exports.VComponent.VComponent.walk (/usr/local/cozy/apps/calendar/node_modules/cozy-ical/lib/index.js:154:25)
    at Function.Event.extractEvents (/usr/local/cozy/apps/calendar/node_modules/cozy-ical/lib/event.js:183:15)
    at /usr/local/cozy/apps/calendar/build/server/controllers/ical.js:117:29
    at /usr/local/cozy/apps/calendar/build/server/models/event.js:71:12
    at /usr/local/cozy/apps/calendar/node_modules/cozydb/lib/cozymodel.js:254:18
    at parseBody (/usr/local/cozy/apps/calendar/node_modules/cozydb/node_modules/request-json-light/main.js:75:10)
[2016-03-13 04:47:46:757] error - calendar:ical | Error: Invalid options: bynmonthday, bynweekday
    at Object.RRule (/usr/local/cozy/apps/calendar/node_modules/cozy-ical/node_modules/rrule/lib/rrule.js:484:15)
    at Function.Event.fromIcal (/usr/local/cozy/apps/calendar/node_modules/cozy-ical/lib/event.js:111:19)
    at /usr/local/cozy/apps/calendar/node_modules/cozy-ical/lib/event.js:185:34
    at VEvent.module.exports.VComponent.VComponent.walk (/usr/local/cozy/apps/calendar/node_modules/cozy-ical/lib/index.js:149:5)
    at VCalendar.module.exports.VComponent.VComponent.walk (/usr/local/cozy/apps/calendar/node_modules/cozy-ical/lib/index.js:154:25)
    at Function.Event.extractEvents (/usr/local/cozy/apps/calendar/node_modules/cozy-ical/lib/event.js:183:15)
    at /usr/local/cozy/apps/calendar/build/server/controllers/ical.js:117:29
    at /usr/local/cozy/apps/calendar/build/server/models/event.js:71:12
    at /usr/local/cozy/apps/calendar/node_modules/cozydb/lib/cozymodel.js:254:18
    at parseBody (/usr/local/cozy/apps/calendar/node_modules/cozydb/node_modules/request-json-light/main.js:75:10)
/usr/local/cozy/apps/calendar/node_modules/printit/main.js:46
      text = JSON.stringify(text);
                  ^

TypeError: Converting circular structure to JSON
    at Object.stringify (native)
    at Logger.stringify (/usr/local/cozy/apps/calendar/node_modules/printit/main.js:46:19)
    at Logger.<anonymous> (/usr/local/cozy/apps/calendar/node_modules/printit/main.js:73:27)
    at Logger.format (/usr/local/cozy/apps/calendar/node_modules/printit/main.js:76:8)
    at Logger.error (/usr/local/cozy/apps/calendar/node_modules/printit/main.js:114:25)
    at /usr/local/cozy/apps/calendar/build/server/controllers/ical.js:125:17
    at /usr/local/cozy/apps/calendar/build/server/models/event.js:71:12
    at /usr/local/cozy/apps/calendar/node_modules/cozydb/lib/cozymodel.js:254:18
    at parseBody (/usr/local/cozy/apps/calendar/node_modules/cozydb/node_modules/request-json-light/main.js:75:10)
    at IncomingMessage.<anonymous> (/usr/local/cozy/apps/calendar/node_modules/cozydb/node_modules/request-json-light/main.js:109:14)
```

**Comment by frankrousseau** [comment]
Thank you @mjog for reporting. We just pushed a new version of the Cozy Calendar. Can you try again?

**Comment by mjog** [comment]
Upgrading to version 1.2.35 seems to have fixed it, thanks!
