### ISSUE TITLE
Can't remove a calendar

### ISSUE THREAD

**Issue by babolivier** [cozy/cozy-calendar#529]
I have a calendar called "Misc" with two events in it that I want to delete. I do so by clicking the arrow in front of the calendar's name, and "Supprimer". Nothing happens, and when I reload the page the calendar is still here. I have this error in the app's log:

```
[2016-05-17 08:43:30:529] error - calendar:client | RangeError: Maximum call stack size exceeded
    at RegExp.[Symbol.replace] (native)
    at String.replace (native)
    at unescapeFormat (https://bren.cozycloud.cc/apps/calendar/javascripts/vendor.js:25161:18)
    at getParseRegexForToken (https://bren.cozycloud.cc/apps/calendar/javascripts/vendor.js:24818:41)
    at makeDateFromStringAndFormat (https://bren.cozycloud.cc/apps/calendar/javascripts/vendor.js:25117:41)
    at parseISO (https://bren.cozycloud.cc/apps/calendar/javascripts/vendor.js:25241:13)
    at makeDateFromString (https://bren.cozycloud.cc/apps/calendar/javascripts/vendor.js:25249:9)
    at makeDateFromInput (https://bren.cozycloud.cc/apps/calendar/javascripts/vendor.js:25273:13)
    at makeMoment (https://bren.cozycloud.cc/apps/calendar/javascripts/vendor.js:25436:13)
    at moment (https://bren.cozycloud.cc/apps/calendar/javascripts/vendor.js:25460:16)
    at Object.exports.toTimezonedMoment (https://bren.cozycloud.cc/apps/calendar/javascripts/app.js:983:7)
```

**Comment by babolivier** [comment]
Nevermind, that was only happening in Brave. Must come from the browser.
